### Numpy
* numpy----Numerical Python
* Numoy is a library in python which is used to built different dimensional arrays

In [17]:
import numpy as np
a=[1,2,3,4,5]
data=np.array(a)
print(data)

[1 2 3 4 5]


In [2]:
a

[1, 2, 3, 4, 5]

In [8]:
data1=np.array([[6,7,8,9],[1,2,3,4]])

In [9]:

data1

array([[6, 7, 8, 9],
       [1, 2, 3, 4]])

In [10]:
data2=np.array([[1,2,3],[3,4,5],[6,7,8]])

In [11]:
data2

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
data1.shape

(2, 4)

In [13]:
data2.shape


(3, 3)

In [25]:
import numpy as np
data=np.arange(0,100)
print(data)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [26]:
data1=data.reshape(10,10)

In [27]:
data1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [32]:
data2=np.linspace(0,8,10)

In [33]:
data2

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

In [37]:
data=np.random.randint(0,20,size=(2,4))
data

array([[ 5, 11,  0,  1],
       [15, 18,  2,  1]])

In [47]:
data=np.ones((4,3),int)
data
print(np.vstack([data,data*10]))
np.hstack([data,data*10])

[[ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [ 1  1  1]
 [10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]


array([[ 1,  1,  1, 10, 10, 10],
       [ 1,  1,  1, 10, 10, 10],
       [ 1,  1,  1, 10, 10, 10],
       [ 1,  1,  1, 10, 10, 10]])

In [44]:
data=np.zeros((4,3),int)
data
np.vstack([data,data*10])

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

### Operators in arrays:

In [58]:
n1=np.array([1,2,3])
n2=np.array([5,6,7])
print(n1+n2)
print(n1-n2)
print(n1*n2)
print(n1//n2)
print(n1**n2)
print(n1%n2)
print(n1&n2)


[ 6  8 10]
[-4 -4 -4]
[ 5 12 21]
[0 0 0]
[   1   64 2187]
[1 2 3]
[1 2 3]


In [59]:
n1.dot(n2)

38

In [61]:
data.T

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [62]:
print(data.transpose())

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [64]:
data.max()

1

In [65]:
n1.max()

3

In [66]:
n2.min()

5

In [69]:
n1.sum()

6

In [70]:
n1.mean()

2.0