### 1.Write a python program to change the order of index in a given series

In [2]:
import pandas as pd

In [24]:
a=pd.DataFrame({'name':['siri','deepu','hari'],'rno':['422','654','345']})

In [25]:
a

name  rno
0   siri  422
1  deepu  654
2   hari  345

In [27]:
a.reindex([2,0,1])

name  rno
2   hari  345
0   siri  422
1  deepu  654

In [20]:
import numpy as np
Exam_data={'name':['Sachin','Ganguly','Kohli','Johnson','Taylor','Waugh',"Yuvaraj",'Kambli','Srinath','Munaf'],'score':[12.5,9,16.5,np.nan,9,20,14.5,np.nan,8,19],'attempts':[1,3,2,3,1,1,2,1,4,5],'qualify':['y','n','n','y','n','y','n','y','n','y']}

In [21]:
labels=['a','b','c','d','e','f','g','h']

In [19]:
Exam_data=pd.DataFrame(Exam_data)

ValueError: arrays must all be same length

## 2.

In [47]:
a=pd.Series([1,2,3,4])
a

0    1
1    2
2    3
3    4
dtype: int64

In [48]:
b=pd.Series([1,2,3,4])
b

0    1
1    2
2    3
3    4
dtype: int64

In [49]:
a+b

0    2
1    4
2    6
3    8
dtype: int64

In [50]:
a-b

0    0
1    0
2    0
3    0
dtype: int64

In [51]:
a*b

0     1
1     4
2     9
3    16
dtype: int64

In [52]:
a/b

0    1.0
1    1.0
2    1.0
3    1.0
dtype: float64

## 8.

In [55]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [56]:
b=np.ravel(a)

In [57]:
b

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
a=np.ravel(a)

In [60]:
a


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
b=np.flatten(a)

AttributeError: module 'numpy' has no attribute 'flatten'

Object `flaten` not found.
